import type { Topic } from "./schema";

export const TOPICS: Topic[] = [
  // Level 1: Explorer (1-2 years) - Concrete, everyday objects
  {
    id: "animal-friends",
    name: "Animal Friends",
    description:
      "Meet friendly farm animals and pets! Perfect for little ones learning their first animal names.",
    learningGoals: [
      "Recognize common farm animals",
      "Associate animal names with their appearance",
      "Build early vocabulary",
    ],
    icon: "🐶",
    level: 1,
    words: [
      "dog",
      "cat",
      "pig",
      "cow",
      "chicken",
      "duck",
      "horse",
      "sheep",
      "rabbit",
      "fish",
    ],
  },
  {
    id: "fruits",
    name: "Fruits",
    description:
      "Discover colorful fruits from the kitchen! Learn to identify delicious fruits by their shapes and colors.",
    learningGoals: [
      "Identify common fruits",
      "Learn fruit names",
      "Connect fruits to everyday eating",
    ],
    icon: "🍎",
    level: 1,
    words: [
      "apple",
      "banana",
      "strawberry",
      "orange",
      "grapes",
      "watermelon",
      "lemon",
      "pear",
      "peach",
      "cherry",
    ],
  },
  {
    id: "vehicles",
    name: "Vehicles",
    description:
      "Things that go! Explore cars, trucks, and more vehicles your child sees every day.",
    learningGoals: [
      "Name common vehicles",
      "Understand that vehicles help us travel",
      "Recognize vehicles in daily life",
    ],
    icon: "🚗",
    level: 1,
    words: [
      "car",
      "bus",
      "train",
      "truck",
      "airplane",
      "boat",
      "bicycle",
      "helicopter",
      "motorcycle",
      "tractor",
    ],
  },
  {
    id: "clothing",
    name: "Clothing",
    description:
      "What do we wear? Learn about everyday clothing items from head to toe.",
    learningGoals: [
      "Identify clothing items",
      "Connect clothes to body parts",
      "Build dressing vocabulary",
    ],
    icon: "👕",
    level: 1,
    words: [
      "shoe",
      "t-shirt",
      "hat",
      "jeans",
      "dress",
      "socks",
      "coat",
      "gloves",
      "scarf",
      "boot",
    ],
  },
  {
    id: "colors",
    name: "Colors",
    description:
      "A rainbow of colors! Practice naming basic colors that are everywhere around us.",
    learningGoals: [
      "Recognize primary colors",
      "Name colors accurately",
      "Notice colors in the environment",
    ],
    icon: "🌈",
    level: 1,
    words: [
      "red",
      "blue",
      "green",
      "yellow",
      "orange",
      "purple",
      "pink",
      "brown",
      "black",
      "white",
    ],
  },

  // Level 2: Discoverer (3-5 years) - Categorization, emotions, attributes
  {
    id: "wild-animals",
    name: "Wild Animals",
    description:
      "Safari time! Discover amazing animals from jungles, oceans, and beyond.",
    learningGoals: [
      "Learn about animals from different habitats",
      "Understand animal diversity",
      "Expand animal vocabulary",
    ],
    icon: "🦁",
    level: 2,
    words: [
      "lion",
      "elephant",
      "giraffe",
      "zebra",
      "monkey",
      "bear",
      "shark",
      "dolphin",
      "butterfly",
      "octopus",
      "penguin",
      "kangaroo",
    ],
  },
  {
    id: "food",
    name: "Food",
    description:
      "Yummy foods from around the world! From pizza to noodles, discover tasty treats.",
    learningGoals: [
      "Identify various foods",
      "Learn food vocabulary",
      "Connect food to meals",
    ],
    icon: "🍕",
    level: 2,
    words: [
      "pizza",
      "ice cream",
      "hamburger",
      "doughnut",
      "popcorn",
      "cake",
      "cookie",
      "bread",
      "cheese",
      "egg",
      "rice",
      "noodle",
    ],
  },
  {
    id: "nature",
    name: "Nature",
    description:
      "Explore the natural world! From sunny skies to snowy mountains, discover nature's wonders.",
    learningGoals: [
      "Identify natural phenomena",
      "Learn about weather and landscapes",
      "Appreciate the natural world",
    ],
    icon: "🌻",
    level: 2,
    words: [
      "sun",
      "rain",
      "rainbow",
      "cloud",
      "snow",
      "star",
      "moon",
      "rose",
      "sunflower",
      "tree",
      "mushroom",
      "clover",
      "mountain",
      "volcano",
      "beach",
      "wave",
      "fire",
      "snowman",
    ],
  },
  {
    id: "emotions",
    name: "Emotions",
    description:
      "How do you feel? Learn to recognize and name different emotions and feelings.",
    learningGoals: [
      "Identify facial expressions",
      "Name common emotions",
      "Build emotional vocabulary",
    ],
    icon: "😊",
    level: 2,
    words: [
      "smiling",
      "sad",
      "angry",
      "fearful",
      "sleepy",
      "love",
      "worried",
      "crying",
      "thinking",
      "confused",
    ],
  },
  {
    id: "shapes",
    name: "Shapes",
    description:
      "Shapes are everywhere! Learn to spot circles, squares, and more geometric friends.",
    learningGoals: [
      "Recognize basic shapes",
      "Find shapes in everyday objects",
      "Build spatial awareness",
    ],
    icon: "⭐",
    level: 2,
    words: [
      "circle",
      "square",
      "triangle",
      "star",
      "red heart",
      "diamond",
      "black circle",
      "white circle",
      "red square",
      "blue square",
    ],
  },

  // Level 3: Scholar (>5 years) - Complex symbols, global awareness
  {
    id: "flags",
    name: "Flags",
    description:
      "Travel the world through flags! Learn to recognize flags from different countries.",
    learningGoals: [
      "Identify country flags",
      "Learn about world geography",
      "Appreciate global diversity",
    ],
    icon: "🌍",
    level: 3,
    words: [
      "United States",
      "Japan",
      "Brazil",
      "France",
      "United Kingdom",
      "Germany",
      "Italy",
      "Canada",
      "Australia",
      "Mexico",
      "China",
      "India",
    ],
  },
  {
    id: "celebrations",
    name: "Celebrations",
    description:
      "Party time! Discover symbols of holidays and celebrations throughout the year.",
    learningGoals: [
      "Recognize celebration symbols",
      "Learn holiday vocabulary",
      "Connect symbols to occasions",
    ],
    icon: "🎉",
    level: 3,
    words: [
      "birthday",
      "christmas",
      "ghost",
      "fireworks",
      "party",
      "gift",
      "balloon",
      "confetti",
      "cake",
      "sparkler",
    ],
  },
  {
    id: "sports",
    name: "Sports",
    description:
      "Game on! Learn about different sports and the equipment used to play them.",
    learningGoals: [
      "Identify sports and equipment",
      "Learn sports vocabulary",
      "Understand physical activities",
    ],
    icon: "⚽",
    level: 3,
    words: [
      "soccer",
      "basketball",
      "tennis",
      "person golfing",
      "skier",
      "baseball",
      "american football",
      "volleyball",
      "hockey",
      "bowling",
    ],
  },
  {
    id: "professions",
    name: "Professions",
    description:
      "What do you want to be? Explore different jobs and the people who help our community.",
    learningGoals: [
      "Identify different professions",
      "Learn about community helpers",
      "Understand what adults do for work",
    ],
    icon: "👨‍⚕️",
    level: 3,
    words: [
      "health worker",
      "cook",
      "artist",
      "pilot",
      "teacher",
      "firefighter",
      "police officer",
      "farmer",
      "scientist",
      "astronaut",
    ],
  },
];
