/**
 * Emoji database with categories for generating game content without LLM.
 * Only includes well-supported emojis (Unicode 6.0-11.0, ~2010-2018).
 * Generated from https://character.construction/emoji-categories
 */
import { shuffle } from "./shuffle";

/**
 *
 * NAME DESIGN:
 * - First name: PRIMARY - used for display, should be specific
 * - Additional names: ALIASES - used for search AND visual similarity grouping
 * - If two emojis share ANY name, they are considered visually similar
 *   (used for de-duplication in game logic)
 */

export interface EmojiItem {
  names: string[]; // First name is primary, others are aliases/group markers
  emoji: string;
}

interface EmojiCategory {
  category: string;
  items: EmojiItem[];
}

const EMOJI_DATABASE: EmojiCategory[] = [
  {
    category: "animals",
    items: [
      { names: ["see no evil monkey", "monkey face"], emoji: "🙈" },
      { names: ["hear no evil monkey", "monkey face"], emoji: "🙉" },
      { names: ["speak no evil monkey", "monkey face"], emoji: "🙊" },
      { names: ["monkey face", "monkey"], emoji: "🐵" },
      { names: ["monkey", "monkey animal"], emoji: "🐒" },
      { names: ["gorilla"], emoji: "🦍" },
      { names: ["dog face", "dog", "puppy"], emoji: "🐶" },
      { names: ["dog", "dog animal"], emoji: "🐕" },
      { names: ["guide dog", "dog animal"], emoji: "🦮" },
      { names: ["poodle", "dog animal"], emoji: "🐩" },
      { names: ["wolf"], emoji: "🐺" },
      { names: ["fox"], emoji: "🦊" },
      { names: ["raccoon"], emoji: "🦝" },
      { names: ["cat face", "cat", "kitty"], emoji: "🐱" },
      { names: ["cat", "cat animal"], emoji: "🐈" },
      { names: ["lion"], emoji: "🦁" },
      { names: ["tiger face", "tiger"], emoji: "🐯" },
      { names: ["tiger", "tiger animal"], emoji: "🐅" },
      { names: ["leopard"], emoji: "🐆" },
      { names: ["horse face", "horse"], emoji: "🐴" },
      { names: ["horse", "horse animal", "racehorse"], emoji: "🐎" },
      { names: ["unicorn"], emoji: "🦄" },
      { names: ["zebra"], emoji: "🦓" },
      { names: ["deer"], emoji: "🦌" },
      { names: ["bison"], emoji: "🦬" },
      { names: ["cow face", "cow"], emoji: "🐮" },
      { names: ["ox", "cow animal"], emoji: "🐂" },
      { names: ["water buffalo", "cow animal"], emoji: "🐃" },
      { names: ["cow", "cow animal"], emoji: "🐄" },
      { names: ["pig face", "pig"], emoji: "🐷" },
      { names: ["pig", "pig animal"], emoji: "🐖" },
      { names: ["boar", "wild pig"], emoji: "🐗" },
      { names: ["pig nose", "pig"], emoji: "🐽" },
      { names: ["ram", "sheep animal"], emoji: "🐏" },
      { names: ["sheep", "sheep animal", "lamb"], emoji: "🐑" },
      { names: ["goat"], emoji: "🐐" },
      { names: ["dromedary camel", "camel"], emoji: "🐪" },
      { names: ["bactrian camel", "camel"], emoji: "🐫" },
      { names: ["llama"], emoji: "🦙" },
      { names: ["giraffe"], emoji: "🦒" },
      { names: ["elephant"], emoji: "🐘" },
      { names: ["rhinoceros", "rhino"], emoji: "🦏" },
      { names: ["hippopotamus", "hippo"], emoji: "🦛" },
      { names: ["mouse face", "mouse"], emoji: "🐭" },
      { names: ["mouse", "mouse animal"], emoji: "🐁" },
      { names: ["rat"], emoji: "🐀" },
      { names: ["hamster"], emoji: "🐹" },
      { names: ["rabbit face", "rabbit", "bunny"], emoji: "🐰" },
      { names: ["rabbit", "rabbit animal", "bunny"], emoji: "🐇" },
      { names: ["beaver"], emoji: "🦫" },
      { names: ["hedgehog"], emoji: "🦔" },
      { names: ["bat"], emoji: "🦇" },
      { names: ["bear face", "bear"], emoji: "🐻" },
      { names: ["koala"], emoji: "🐨" },
      { names: ["panda"], emoji: "🐼" },
      { names: ["kangaroo"], emoji: "🦘" },
      { names: ["badger"], emoji: "🦡" },
      { names: ["paw prints"], emoji: "🐾" },
      { names: ["turkey", "bird animal"], emoji: "🦃" },
      { names: ["chicken", "bird animal"], emoji: "🐔" },
      { names: ["rooster", "bird animal"], emoji: "🐓" },
      { names: ["hatching chick", "chick", "bird animal"], emoji: "🐣" },
      { names: ["baby chick", "chick", "bird animal"], emoji: "🐤" },
      { names: ["front facing chick", "chick", "bird animal"], emoji: "🐥" },
      { names: ["bird"], emoji: "🐦" },
      { names: ["penguin", "bird animal"], emoji: "🐧" },
      { names: ["eagle", "bird animal"], emoji: "🦅" },
      { names: ["duck", "bird animal"], emoji: "🦆" },
      { names: ["swan", "bird animal"], emoji: "🦢" },
      { names: ["owl", "bird animal"], emoji: "🦉" },
      { names: ["peacock", "bird animal"], emoji: "🦚" },
      { names: ["parrot", "bird animal"], emoji: "🦜" },
      { names: ["frog"], emoji: "🐸" },
      { names: ["crocodile"], emoji: "🐊" },
      { names: ["turtle"], emoji: "🐢" },
      { names: ["lizard"], emoji: "🦎" },
      { names: ["snake"], emoji: "🐍" },
      { names: ["dragon face", "dragon"], emoji: "🐲" },
      { names: ["dragon", "dragon animal"], emoji: "🐉" },
      { names: ["brontosaurus", "dinosaur"], emoji: "🦕" },
      { names: ["t-rex", "dinosaur"], emoji: "🦖" },
      { names: ["spouting whale", "whale"], emoji: "🐳" },
      { names: ["whale", "whale animal"], emoji: "🐋" },
      { names: ["dolphin"], emoji: "🐬" },
      { names: ["seal"], emoji: "🦭" },
      { names: ["fish"], emoji: "🐟" },
      { names: ["tropical fish", "fish animal"], emoji: "🐠" },
      { names: ["blowfish", "fish animal"], emoji: "🐡" },
      { names: ["shark"], emoji: "🦈" },
      { names: ["octopus"], emoji: "🐙" },
      { names: ["spiral shell", "seashell"], emoji: "🐚" },
      { names: ["crab"], emoji: "🦀" },
      { names: ["lobster"], emoji: "🦞" },
      { names: ["shrimp"], emoji: "🦐" },
      { names: ["squid"], emoji: "🦑" },
      { names: ["snail"], emoji: "🐌" },
      { names: ["butterfly"], emoji: "🦋" },
      { names: ["caterpillar", "bug"], emoji: "🐛" },
      { names: ["ant"], emoji: "🐜" },
      { names: ["honeybee", "bee"], emoji: "🐝" },
      { names: ["ladybug"], emoji: "🐞" },
      { names: ["cricket"], emoji: "🦗" },
      { names: ["scorpion"], emoji: "🦂" },
      { names: ["mosquito"], emoji: "🦟" },
      { names: ["microbe", "germ"], emoji: "🦠" },
    ],
  },
  {
    category: "fruits",
    items: [
      { names: ["grapes"], emoji: "🍇" },
      { names: ["melon", "cantaloupe"], emoji: "🍈" },
      { names: ["watermelon"], emoji: "🍉" },
      { names: ["tangerine", "orange fruit"], emoji: "🍊" },
      { names: ["lemon"], emoji: "🍋" },
      { names: ["banana"], emoji: "🍌" },
      { names: ["pineapple"], emoji: "🍍" },
      { names: ["mango"], emoji: "🥭" },
      { names: ["red apple", "apple"], emoji: "🍎" },
      { names: ["green apple", "apple"], emoji: "🍏" },
      { names: ["pear"], emoji: "🍐" },
      { names: ["peach"], emoji: "🍑" },
      { names: ["cherries"], emoji: "🍒" },
      { names: ["strawberry"], emoji: "🍓" },
      { names: ["kiwi fruit"], emoji: "🥝" },
      { names: ["tomato"], emoji: "🍅" },
      { names: ["coconut"], emoji: "🥥" },
    ],
  },
  {
    category: "vegetables",
    items: [
      { names: ["avocado"], emoji: "🥑" },
      { names: ["eggplant"], emoji: "🍆" },
      { names: ["potato"], emoji: "🥔" },
      { names: ["carrot"], emoji: "🥕" },
      { names: ["corn"], emoji: "🌽" },
      { names: ["cucumber"], emoji: "🥒" },
      { names: ["leafy green", "lettuce"], emoji: "🥬" },
      { names: ["broccoli"], emoji: "🥦" },
      { names: ["peanuts"], emoji: "🥜" },
      { names: ["chestnut"], emoji: "🌰" },
    ],
  },
  {
    category: "food",
    items: [
      { names: ["bread"], emoji: "🍞" },
      { names: ["croissant"], emoji: "🥐" },
      { names: ["baguette"], emoji: "🥖" },
      { names: ["pretzel"], emoji: "🥨" },
      { names: ["bagel"], emoji: "🥯" },
      { names: ["pancakes"], emoji: "🥞" },
      { names: ["cheese"], emoji: "🧀" },
      { names: ["meat on bone"], emoji: "🍖" },
      { names: ["poultry leg", "drumstick"], emoji: "🍗" },
      { names: ["cut of meat", "steak"], emoji: "🥩" },
      { names: ["bacon"], emoji: "🥓" },
      { names: ["hamburger", "burger"], emoji: "🍔" },
      { names: ["french fries", "fries"], emoji: "🍟" },
      { names: ["pizza"], emoji: "🍕" },
      { names: ["hot dog"], emoji: "🌭" },
      { names: ["sandwich"], emoji: "🥪" },
      { names: ["taco"], emoji: "🌮" },
      { names: ["burrito"], emoji: "🌯" },
      { names: ["stuffed flatbread", "pita"], emoji: "🥙" },
      { names: ["egg"], emoji: "🥚" },
      { names: ["cooking", "fried egg"], emoji: "🍳" },
      { names: ["shallow pan of food"], emoji: "🥘" },
      { names: ["pot of food", "stew"], emoji: "🍲" },
      { names: ["bowl with spoon", "cereal"], emoji: "🥣" },
      { names: ["green salad", "salad"], emoji: "🥗" },
      { names: ["popcorn"], emoji: "🍿" },
      { names: ["canned food"], emoji: "🥫" },
      { names: ["bento box"], emoji: "🍱" },
      { names: ["rice cracker"], emoji: "🍘" },
      { names: ["rice ball", "onigiri"], emoji: "🍙" },
      { names: ["cooked rice"], emoji: "🍚" },
      { names: ["curry rice"], emoji: "🍛" },
      { names: ["steaming bowl", "ramen", "noodles"], emoji: "🍜" },
      { names: ["spaghetti", "pasta"], emoji: "🍝" },
      { names: ["roasted sweet potato"], emoji: "🍠" },
      { names: ["oden"], emoji: "🍢" },
      { names: ["sushi"], emoji: "🍣" },
      { names: ["fried shrimp"], emoji: "🍤" },
      { names: ["fish cake"], emoji: "🍥" },
      { names: ["moon cake"], emoji: "🥮" },
      { names: ["dango"], emoji: "🍡" },
      { names: ["dumpling"], emoji: "🥟" },
      { names: ["fortune cookie"], emoji: "🥠" },
      { names: ["takeout box"], emoji: "🥡" },
      { names: ["soft ice cream", "ice cream cone"], emoji: "🍦" },
      { names: ["shaved ice"], emoji: "🍧" },
      { names: ["ice cream", "ice cream bowl"], emoji: "🍨" },
      { names: ["doughnut", "donut"], emoji: "🍩" },
      { names: ["cookie"], emoji: "🍪" },
      { names: ["birthday cake", "cake"], emoji: "🎂" },
      { names: ["shortcake", "cake slice"], emoji: "🍰" },
      { names: ["pie"], emoji: "🥧" },
      { names: ["chocolate bar"], emoji: "🍫" },
      { names: ["candy"], emoji: "🍬" },
      { names: ["lollipop"], emoji: "🍭" },
      { names: ["custard", "pudding"], emoji: "🍮" },
      { names: ["honey pot"], emoji: "🍯" },
    ],
  },
  {
    category: "drinks",
    items: [
      { names: ["baby bottle"], emoji: "🍼" },
      { names: ["glass of milk", "milk"], emoji: "🥛" },
      { names: ["hot beverage", "coffee"], emoji: "☕" },
      { names: ["teacup", "tea"], emoji: "🍵" },
      { names: ["sake"], emoji: "🍶" },
      { names: ["bottle with popping cork", "champagne"], emoji: "🍾" },
      { names: ["wine glass", "wine"], emoji: "🍷" },
      { names: ["cocktail glass", "martini"], emoji: "🍸" },
      { names: ["tropical drink"], emoji: "🍹" },
      { names: ["beer mug", "beer"], emoji: "🍺" },
      { names: ["clinking beer mugs", "cheers"], emoji: "🍻" },
      { names: ["clinking glasses", "toast"], emoji: "🥂" },
      { names: ["tumbler glass", "whiskey"], emoji: "🥃" },
      { names: ["cup with straw", "soda"], emoji: "🥤" },
    ],
  },
  {
    category: "nature",
    items: [
      { names: ["bouquet", "flower"], emoji: "💐" },
      { names: ["cherry blossom", "flower"], emoji: "🌸" },
      { names: ["white flower", "flower"], emoji: "💮" },
      { names: ["rose", "flower"], emoji: "🌹" },
      { names: ["wilted flower", "flower"], emoji: "🥀" },
      { names: ["hibiscus", "flower"], emoji: "🌺" },
      { names: ["sunflower", "flower"], emoji: "🌻" },
      { names: ["blossom", "flower"], emoji: "🌼" },
      { names: ["tulip", "flower"], emoji: "🌷" },
      { names: ["seedling", "sprout"], emoji: "🌱" },
      { names: ["evergreen tree", "tree"], emoji: "🌲" },
      { names: ["deciduous tree", "tree"], emoji: "🌳" },
      { names: ["palm tree", "tree"], emoji: "🌴" },
      { names: ["cactus"], emoji: "🌵" },
      { names: ["sheaf of rice"], emoji: "🌾" },
      { names: ["herb"], emoji: "🌿" },
      { names: ["four leaf clover", "clover"], emoji: "🍀" },
      { names: ["maple leaf", "leaf"], emoji: "🍁" },
      { names: ["fallen leaf", "leaf"], emoji: "🍂" },
      { names: ["leaf fluttering", "leaf"], emoji: "🍃" },
      { names: ["mushroom"], emoji: "🍄" },
      { names: ["globe europe africa", "globe"], emoji: "🌍" },
      { names: ["globe americas", "globe"], emoji: "🌎" },
      { names: ["globe asia australia", "globe"], emoji: "🌏" },
      { names: ["globe with meridians", "globe"], emoji: "🌐" },
      { names: ["silhouette of japan"], emoji: "🗾" },
      { names: ["landslide"], emoji: "🛘" },
      { names: ["volcano"], emoji: "🌋" },
      { names: ["mount fuji", "mountain"], emoji: "🗻" },
    ],
  },
  {
    category: "weather",
    items: [
      { names: ["new moon", "moon"], emoji: "🌑" },
      { names: ["waxing crescent moon", "moon"], emoji: "🌒" },
      { names: ["first quarter moon", "moon"], emoji: "🌓" },
      { names: ["waxing gibbous moon", "moon"], emoji: "🌔" },
      { names: ["full moon", "moon"], emoji: "🌕" },
      { names: ["waning gibbous moon", "moon"], emoji: "🌖" },
      { names: ["last quarter moon", "moon"], emoji: "🌗" },
      { names: ["waning crescent moon", "moon"], emoji: "🌘" },
      { names: ["crescent moon", "moon"], emoji: "🌙" },
      { names: ["new moon face", "moon"], emoji: "🌚" },
      { names: ["first quarter moon face", "moon"], emoji: "🌛" },
      { names: ["last quarter moon face", "moon"], emoji: "🌜" },
      { names: ["full moon face", "moon"], emoji: "🌝" },
      { names: ["sun with face", "sun"], emoji: "🌞" },
      { names: ["star"], emoji: "⭐" },
      { names: ["glowing star", "star"], emoji: "🌟" },
      { names: ["shooting star", "star"], emoji: "🌠" },
      { names: ["milky way", "galaxy"], emoji: "🌌" },
      { names: ["sun behind cloud", "partly cloudy"], emoji: "⛅" },
      { names: ["cyclone"], emoji: "🌀" },
      { names: ["rainbow"], emoji: "🌈" },
      { names: ["closed umbrella", "umbrella"], emoji: "🌂" },
      { names: ["umbrella with rain drops", "rain"], emoji: "☔" },
      { names: ["high voltage", "lightning", "zap"], emoji: "⚡" },
      { names: ["snowman without snow", "snowman"], emoji: "⛄" },
      { names: ["fire", "flame"], emoji: "🔥" },
      { names: ["droplet", "water drop"], emoji: "💧" },
      { names: ["water wave", "ocean wave"], emoji: "🌊" },
    ],
  },
  {
    category: "vehicles",
    items: [
      { names: ["locomotive", "train"], emoji: "🚂" },
      { names: ["railway car", "train car"], emoji: "🚃" },
      { names: ["high speed train", "train"], emoji: "🚄" },
      { names: ["bullet train", "train"], emoji: "🚅" },
      { names: ["train"], emoji: "🚆" },
      { names: ["metro", "subway"], emoji: "🚇" },
      { names: ["light rail", "train"], emoji: "🚈" },
      { names: ["station"], emoji: "🚉" },
      { names: ["tram", "train"], emoji: "🚊" },
      { names: ["monorail", "train"], emoji: "🚝" },
      { names: ["mountain railway", "train"], emoji: "🚞" },
      { names: ["tram car", "train"], emoji: "🚋" },
      { names: ["bus"], emoji: "🚌" },
      { names: ["oncoming bus", "bus"], emoji: "🚍" },
      { names: ["trolleybus", "bus"], emoji: "🚎" },
      { names: ["minibus", "bus"], emoji: "🚐" },
      { names: ["ambulance"], emoji: "🚑" },
      { names: ["fire engine"], emoji: "🚒" },
      { names: ["police car", "car"], emoji: "🚓" },
      { names: ["oncoming police car", "car"], emoji: "🚔" },
      { names: ["taxi", "car"], emoji: "🚕" },
      { names: ["oncoming taxi", "car"], emoji: "🚖" },
      { names: ["automobile", "car"], emoji: "🚗" },
      { names: ["oncoming automobile", "car"], emoji: "🚘" },
      { names: ["sport utility vehicle", "suv", "car"], emoji: "🚙" },
      { names: ["delivery truck", "truck"], emoji: "🚚" },
      { names: ["articulated lorry", "truck"], emoji: "🚛" },
      { names: ["tractor"], emoji: "🚜" },
      { names: ["motor scooter", "scooter"], emoji: "🛵" },
      { names: ["manual wheelchair"], emoji: "🦽" },
      { names: ["motorized wheelchair"], emoji: "🦼" },
      { names: ["bicycle", "bike"], emoji: "🚲" },
      { names: ["kick scooter"], emoji: "🛴" },
      { names: ["bus stop"], emoji: "🚏" },
      { names: ["fuel pump", "gas station"], emoji: "⛽" },
      { names: ["wheel"], emoji: "🛞" },
      { names: ["police car light"], emoji: "🚨" },
      { names: ["horizontal traffic light", "traffic light"], emoji: "🚥" },
      { names: ["vertical traffic light", "traffic light"], emoji: "🚦" },
      { names: ["stop sign"], emoji: "🛑" },
      { names: ["construction sign"], emoji: "🚧" },
      { names: ["anchor"], emoji: "⚓" },
      { names: ["ring buoy"], emoji: "🛟" },
      { names: ["sailboat", "boat"], emoji: "⛵" },
      { names: ["canoe"], emoji: "🛶" },
      { names: ["speedboat", "boat"], emoji: "🚤" },
      { names: ["ship"], emoji: "🚢" },
      { names: ["airplane departure", "plane"], emoji: "🛫" },
      { names: ["airplane arrival", "plane"], emoji: "🛬" },
      { names: ["seat"], emoji: "💺" },
      { names: ["helicopter"], emoji: "🚁" },
      { names: ["suspension railway"], emoji: "🚟" },
      { names: ["mountain cableway"], emoji: "🚠" },
      { names: ["aerial tramway"], emoji: "🚡" },
      { names: ["rocket"], emoji: "🚀" },
      { names: ["flying saucer", "ufo"], emoji: "🛸" },
    ],
  },
  {
    category: "places",
    items: [
      { names: ["hut"], emoji: "🛖" },
      { names: ["house"], emoji: "🏠" },
      { names: ["house with garden"], emoji: "🏡" },
      { names: ["office building"], emoji: "🏢" },
      { names: ["japanese post office"], emoji: "🏣" },
      { names: ["post office"], emoji: "🏤" },
      { names: ["hospital"], emoji: "🏥" },
      { names: ["bank"], emoji: "🏦" },
      { names: ["hotel"], emoji: "🏨" },
      { names: ["love hotel"], emoji: "🏩" },
      { names: ["convenience store"], emoji: "🏪" },
      { names: ["school"], emoji: "🏫" },
      { names: ["department store"], emoji: "🏬" },
      { names: ["factory"], emoji: "🏭" },
      { names: ["japanese castle", "castle"], emoji: "🏯" },
      { names: ["castle", "european castle"], emoji: "🏰" },
      { names: ["wedding chapel"], emoji: "💒" },
      { names: ["tokyo tower"], emoji: "🗼" },
      { names: ["statue of liberty"], emoji: "🗽" },
      { names: ["church"], emoji: "⛪" },
      { names: ["mosque"], emoji: "🕌" },
      { names: ["hindu temple"], emoji: "🛕" },
      { names: ["synagogue"], emoji: "🕍" },
      { names: ["kaaba"], emoji: "🕋" },
      { names: ["fountain"], emoji: "⛲" },
      { names: ["tent"], emoji: "⛺" },
      { names: ["foggy"], emoji: "🌁" },
      { names: ["night with stars"], emoji: "🌃" },
      { names: ["sunrise over mountains"], emoji: "🌄" },
      { names: ["sunrise"], emoji: "🌅" },
      { names: ["cityscape at dusk"], emoji: "🌆" },
      { names: ["sunset"], emoji: "🌇" },
      { names: ["bridge at night"], emoji: "🌉" },
      { names: ["carousel horse"], emoji: "🎠" },
      { names: ["playground slide"], emoji: "🛝" },
      { names: ["ferris wheel"], emoji: "🎡" },
      { names: ["roller coaster"], emoji: "🎢" },
      { names: ["barber pole"], emoji: "💈" },
      { names: ["circus tent"], emoji: "🎪" },
    ],
  },
  {
    category: "time",
    items: [
      { names: ["hourglass done"], emoji: "⌛" },
      { names: ["hourglass not done", "hourglass"], emoji: "⏳" },
      { names: ["watch"], emoji: "⌚" },
      { names: ["alarm clock", "clock"], emoji: "⏰" },
      { names: ["twelve oclock", "clock"], emoji: "🕛" },
      { names: ["twelve thirty", "clock"], emoji: "🕧" },
      { names: ["one oclock", "clock"], emoji: "🕐" },
      { names: ["one thirty", "clock"], emoji: "🕜" },
      { names: ["two oclock", "clock"], emoji: "🕑" },
      { names: ["two thirty", "clock"], emoji: "🕝" },
      { names: ["three oclock", "clock"], emoji: "🕒" },
      { names: ["three thirty", "clock"], emoji: "🕞" },
      { names: ["four oclock", "clock"], emoji: "🕓" },
      { names: ["four thirty", "clock"], emoji: "🕟" },
      { names: ["five oclock", "clock"], emoji: "🕔" },
      { names: ["five thirty", "clock"], emoji: "🕠" },
      { names: ["six oclock", "clock"], emoji: "🕕" },
      { names: ["six thirty", "clock"], emoji: "🕡" },
      { names: ["seven oclock", "clock"], emoji: "🕖" },
      { names: ["seven thirty", "clock"], emoji: "🕢" },
      { names: ["eight oclock", "clock"], emoji: "🕗" },
      { names: ["eight thirty", "clock"], emoji: "🕣" },
      { names: ["nine oclock", "clock"], emoji: "🕘" },
      { names: ["nine thirty", "clock"], emoji: "🕤" },
      { names: ["ten oclock", "clock"], emoji: "🕙" },
      { names: ["ten thirty", "clock"], emoji: "🕥" },
      { names: ["eleven oclock", "clock"], emoji: "🕚" },
      { names: ["eleven thirty", "clock"], emoji: "🕦" },
    ],
  },
  {
    category: "objects",
    items: [
      { names: ["chopsticks"], emoji: "🥢" },
      { names: ["fork and knife"], emoji: "🍴" },
      { names: ["spoon"], emoji: "🥄" },
      { names: ["kitchen knife"], emoji: "🔪" },
      { names: ["amphora"], emoji: "🏺" },
      { names: ["trophy"], emoji: "🏆" },
      { names: ["sports medal", "medal"], emoji: "🏅" },
      { names: ["gold medal", "first place", "medal"], emoji: "🥇" },
      { names: ["silver medal", "second place", "medal"], emoji: "🥈" },
      { names: ["bronze medal", "third place", "medal"], emoji: "🥉" },
      { names: ["mobile phone", "cellphone"], emoji: "📱" },
      { names: ["mobile phone with arrow"], emoji: "📲" },
      { names: ["telephone receiver"], emoji: "📞" },
      { names: ["pager"], emoji: "📟" },
      { names: ["fax machine"], emoji: "📠" },
      { names: ["battery"], emoji: "🔋" },
      { names: ["electric plug"], emoji: "🔌" },
      { names: ["laptop"], emoji: "💻" },
      { names: ["computer disk"], emoji: "💽" },
      { names: ["floppy disk"], emoji: "💾" },
      { names: ["optical disk", "cd"], emoji: "💿" },
      { names: ["dvd"], emoji: "📀" },
      { names: ["movie camera"], emoji: "🎥" },
      { names: ["clapper board"], emoji: "🎬" },
      { names: ["television", "tv"], emoji: "📺" },
      { names: ["camera"], emoji: "📷" },
      { names: ["camera with flash", "camera"], emoji: "📸" },
      { names: ["video camera"], emoji: "📹" },
      { names: ["videocassette"], emoji: "📼" },
      {
        names: ["magnifying glass tilted left", "magnifying glass"],
        emoji: "🔍",
      },
      {
        names: ["magnifying glass tilted right", "magnifying glass"],
        emoji: "🔎",
      },
      { names: ["light bulb"], emoji: "💡" },
      { names: ["flashlight"], emoji: "🔦" },
      { names: ["red paper lantern"], emoji: "🏮" },
      { names: ["money bag"], emoji: "💰" },
      { names: ["yen banknote", "money"], emoji: "💴" },
      { names: ["dollar banknote", "money"], emoji: "💵" },
      { names: ["euro banknote", "money"], emoji: "💶" },
      { names: ["pound banknote", "money"], emoji: "💷" },
      { names: ["money with wings"], emoji: "💸" },
      { names: ["credit card"], emoji: "💳" },
      { names: ["chart increasing with yen"], emoji: "💹" },
      { names: ["e-mail", "mail"], emoji: "📧" },
      { names: ["incoming envelope", "mail"], emoji: "📨" },
      { names: ["envelope with arrow", "mail"], emoji: "📩" },
      { names: ["outbox tray"], emoji: "📤" },
      { names: ["inbox tray"], emoji: "📥" },
      { names: ["package", "box"], emoji: "📦" },
      { names: ["closed mailbox with raised flag", "mailbox"], emoji: "📫" },
      { names: ["closed mailbox with lowered flag", "mailbox"], emoji: "📪" },
      { names: ["open mailbox with raised flag", "mailbox"], emoji: "📬" },
      { names: ["open mailbox with lowered flag", "mailbox"], emoji: "📭" },
      { names: ["postbox", "mailbox"], emoji: "📮" },
      { names: ["locked", "lock"], emoji: "🔒" },
      { names: ["unlocked", "lock"], emoji: "🔓" },
      { names: ["locked with pen", "lock"], emoji: "🔏" },
      { names: ["locked with key", "lock"], emoji: "🔐" },
      { names: ["key"], emoji: "🔑" },
      { names: ["door"], emoji: "🚪" },
      { names: ["elevator"], emoji: "🛗" },
      { names: ["toilet"], emoji: "🚽" },
      { names: ["shower"], emoji: "🚿" },
      { names: ["bathtub"], emoji: "🛁" },
      { names: ["shopping cart"], emoji: "🛒" },
      { names: ["cigarette"], emoji: "🚬" },
      { names: ["moai"], emoji: "🗿" },
    ],
  },
  {
    category: "tools",
    items: [
      { names: ["hammer"], emoji: "🔨" },
      { names: ["bomb"], emoji: "💣" },
      { names: ["bow and arrow"], emoji: "🏹" },
      { names: ["wrench"], emoji: "🔧" },
      { names: ["nut and bolt"], emoji: "🔩" },
      { names: ["white cane"], emoji: "🦯" },
      { names: ["link"], emoji: "🔗" },
    ],
  },
  {
    category: "school",
    items: [
      { names: ["notebook with decorative cover", "book"], emoji: "📔" },
      { names: ["closed book", "book"], emoji: "📕" },
      { names: ["open book", "book"], emoji: "📖" },
      { names: ["green book", "book"], emoji: "📗" },
      { names: ["blue book", "book"], emoji: "📘" },
      { names: ["orange book", "book"], emoji: "📙" },
      { names: ["books"], emoji: "📚" },
      { names: ["notebook", "book"], emoji: "📓" },
      { names: ["ledger", "book"], emoji: "📒" },
      { names: ["page with curl"], emoji: "📃" },
      { names: ["scroll"], emoji: "📜" },
      { names: ["page facing up"], emoji: "📄" },
      { names: ["newspaper"], emoji: "📰" },
      { names: ["bookmark tabs"], emoji: "📑" },
      { names: ["bookmark"], emoji: "🔖" },
      { names: ["memo"], emoji: "📝" },
      { names: ["briefcase"], emoji: "💼" },
      { names: ["file folder", "folder"], emoji: "📁" },
      { names: ["open file folder", "folder"], emoji: "📂" },
      { names: ["calendar"], emoji: "📅" },
      { names: ["tear off calendar", "calendar"], emoji: "📆" },
      { names: ["card index"], emoji: "📇" },
      { names: ["chart increasing"], emoji: "📈" },
      { names: ["chart decreasing"], emoji: "📉" },
      { names: ["bar chart"], emoji: "📊" },
      { names: ["clipboard"], emoji: "📋" },
      { names: ["pushpin"], emoji: "📌" },
      { names: ["round pushpin"], emoji: "📍" },
      { names: ["paperclip"], emoji: "📎" },
      { names: ["straight ruler", "ruler"], emoji: "📏" },
      { names: ["triangular ruler", "ruler"], emoji: "📐" },
    ],
  },
  {
    category: "medical",
    items: [
      { names: ["microscope"], emoji: "🔬" },
      { names: ["telescope"], emoji: "🔭" },
      { names: ["satellite antenna"], emoji: "📡" },
      { names: ["syringe"], emoji: "💉" },
      { names: ["pill"], emoji: "💊" },
    ],
  },
  {
    category: "clothing",
    items: [
      { names: ["glasses"], emoji: "👓" },
      { names: ["goggles"], emoji: "🥽" },
      { names: ["lab coat"], emoji: "🥼" },
      { names: ["safety vest"], emoji: "🦺" },
      { names: ["necktie"], emoji: "👔" },
      { names: ["t-shirt"], emoji: "👕" },
      { names: ["jeans"], emoji: "👖" },
      { names: ["dress"], emoji: "👗" },
      { names: ["kimono"], emoji: "👘" },
      { names: ["sari"], emoji: "🥻" },
      { names: ["bikini"], emoji: "👙" },
      { names: ["womans clothes"], emoji: "👚" },
      { names: ["purse"], emoji: "👛" },
      { names: ["handbag"], emoji: "👜" },
      { names: ["clutch bag"], emoji: "👝" },
      { names: ["backpack"], emoji: "🎒" },
      { names: ["mans shoe", "shoe"], emoji: "👞" },
      { names: ["running shoe", "sneaker", "shoe"], emoji: "👟" },
      { names: ["hiking boot", "boot"], emoji: "🥾" },
      { names: ["flat shoe", "shoe"], emoji: "🥿" },
      { names: ["high heeled shoe", "heel"], emoji: "👠" },
      { names: ["womans sandal", "sandal"], emoji: "👡" },
      { names: ["womans boot", "boot"], emoji: "👢" },
      { names: ["crown"], emoji: "👑" },
      { names: ["womans hat", "hat"], emoji: "👒" },
      { names: ["top hat", "hat"], emoji: "🎩" },
      { names: ["graduation cap"], emoji: "🎓" },
      { names: ["prayer beads"], emoji: "📿" },
      { names: ["lipstick"], emoji: "💄" },
      { names: ["ring"], emoji: "💍" },
      { names: ["gem stone", "diamond"], emoji: "💎" },
    ],
  },
  {
    category: "sports",
    items: [
      { names: ["person fencing"], emoji: "🤺" },
      { names: ["horse racing"], emoji: "🏇" },
      { names: ["snowboarder"], emoji: "🏂" },
      { names: ["surfer"], emoji: "🏄" },
      { names: ["person rowing"], emoji: "🚣" },
      { names: ["swimmer"], emoji: "🏊" },
      { names: ["cyclist"], emoji: "🚴" },
      { names: ["mountain biker"], emoji: "🚵" },
      { names: ["person cartwheeling"], emoji: "🤸" },
      { names: ["people wrestling"], emoji: "🤼" },
      { names: ["person playing water polo"], emoji: "🤽" },
      { names: ["person playing handball"], emoji: "🤾" },
      { names: ["person juggling"], emoji: "🤹" },
      { names: ["soccer ball"], emoji: "⚽" },
      { names: ["baseball"], emoji: "⚾" },
      { names: ["softball", "baseball"], emoji: "🥎" },
      { names: ["basketball"], emoji: "🏀" },
      { names: ["volleyball"], emoji: "🏐" },
      { names: ["american football"], emoji: "🏈" },
      { names: ["rugby football"], emoji: "🏉" },
      { names: ["tennis"], emoji: "🎾" },
      { names: ["flying disc", "frisbee"], emoji: "🥏" },
      { names: ["bowling"], emoji: "🎳" },
      { names: ["cricket game"], emoji: "🏏" },
      { names: ["field hockey"], emoji: "🏑" },
      { names: ["ice hockey"], emoji: "🏒" },
      { names: ["lacrosse"], emoji: "🥍" },
      { names: ["ping pong", "table tennis"], emoji: "🏓" },
      { names: ["badminton"], emoji: "🏸" },
      { names: ["boxing glove"], emoji: "🥊" },
      { names: ["martial arts uniform"], emoji: "🥋" },
      { names: ["goal net"], emoji: "🥅" },
      { names: ["flag in hole", "golf"], emoji: "⛳" },
      { names: ["fishing pole"], emoji: "🎣" },
      { names: ["diving mask"], emoji: "🤿" },
      { names: ["running shirt"], emoji: "🎽" },
      { names: ["skis"], emoji: "🎿" },
      { names: ["sled"], emoji: "🛷" },
      { names: ["curling stone"], emoji: "🥌" },
    ],
  },
  {
    category: "games",
    items: [
      { names: ["direct hit", "bullseye", "target"], emoji: "🎯" },
      { names: ["water pistol"], emoji: "🔫" },
      { names: ["pool 8 ball", "billiards"], emoji: "🎱" },
      { names: ["crystal ball"], emoji: "🔮" },
      { names: ["video game", "game controller"], emoji: "🎮" },
      { names: ["slot machine"], emoji: "🎰" },
      { names: ["game die", "dice"], emoji: "🎲" },
      { names: ["joker", "playing card"], emoji: "🃏" },
      { names: ["mahjong red dragon"], emoji: "🀄" },
      { names: ["flower playing cards"], emoji: "🎴" },
    ],
  },
  {
    category: "music",
    items: [
      { names: ["muted speaker"], emoji: "🔇" },
      { names: ["speaker low volume", "speaker"], emoji: "🔈" },
      { names: ["speaker medium volume", "speaker"], emoji: "🔉" },
      { names: ["speaker high volume", "speaker"], emoji: "🔊" },
      { names: ["loudspeaker"], emoji: "📢" },
      { names: ["megaphone"], emoji: "📣" },
      { names: ["postal horn"], emoji: "📯" },
      { names: ["bell"], emoji: "🔔" },
      { names: ["bell with slash"], emoji: "🔕" },
      { names: ["musical score"], emoji: "🎼" },
      { names: ["musical note", "music note"], emoji: "🎵" },
      { names: ["musical notes", "music notes"], emoji: "🎶" },
      { names: ["microphone"], emoji: "🎤" },
      { names: ["headphone"], emoji: "🎧" },
      { names: ["radio"], emoji: "📻" },
      { names: ["saxophone"], emoji: "🎷" },
      { names: ["trumpet"], emoji: "🎺" },
      { names: ["guitar"], emoji: "🎸" },
      { names: ["musical keyboard", "piano"], emoji: "🎹" },
      { names: ["violin"], emoji: "🎻" },
      { names: ["drum"], emoji: "🥁" },
    ],
  },
  {
    category: "arts",
    items: [
      { names: ["performing arts", "theater masks"], emoji: "🎭" },
      { names: ["artist palette", "painting"], emoji: "🎨" },
    ],
  },
  {
    category: "shapes",
    items: [
      { names: ["love letter"], emoji: "💌" },
      { names: ["heart with arrow", "cupid", "heart"], emoji: "💘" },
      { names: ["heart with ribbon", "heart"], emoji: "💝" },
      { names: ["sparkling heart", "heart"], emoji: "💖" },
      { names: ["growing heart", "heart"], emoji: "💗" },
      { names: ["beating heart", "heart"], emoji: "💓" },
      { names: ["revolving hearts", "heart"], emoji: "💞" },
      { names: ["two hearts", "heart"], emoji: "💕" },
      { names: ["heart decoration", "heart"], emoji: "💟" },
      { names: ["broken heart", "heart"], emoji: "💔" },
      { names: ["yellow heart", "heart"], emoji: "💛" },
      { names: ["green heart", "heart"], emoji: "💚" },
      { names: ["blue heart", "heart"], emoji: "💙" },
      { names: ["purple heart", "heart"], emoji: "💜" },
      { names: ["black heart", "heart"], emoji: "🖤" },
      { names: ["red circle", "circle"], emoji: "🔴" },
      { names: ["orange circle", "circle"], emoji: "🟠" },
      { names: ["yellow circle", "circle"], emoji: "🟡" },
      { names: ["green circle", "circle"], emoji: "🟢" },
      { names: ["blue circle", "circle"], emoji: "🔵" },
      { names: ["purple circle", "circle"], emoji: "🟣" },
      { names: ["brown circle", "circle"], emoji: "🟤" },
      { names: ["black circle", "circle"], emoji: "⚫" },
      { names: ["white circle", "circle"], emoji: "⚪" },
      { names: ["red square", "square"], emoji: "🟥" },
      { names: ["orange square", "square"], emoji: "🟧" },
      { names: ["yellow square", "square"], emoji: "🟨" },
      { names: ["green square", "square"], emoji: "🟩" },
      { names: ["blue square", "square"], emoji: "🟦" },
      { names: ["purple square", "square"], emoji: "🟪" },
      { names: ["brown square", "square"], emoji: "🟫" },
      { names: ["black large square", "square"], emoji: "⬛" },
      { names: ["white large square", "square"], emoji: "⬜" },
      { names: ["black medium small square", "square"], emoji: "◾" },
      { names: ["white medium small square", "square"], emoji: "◽" },
      { names: ["large orange diamond", "diamond shape"], emoji: "🔶" },
      { names: ["large blue diamond", "diamond shape"], emoji: "🔷" },
      { names: ["small orange diamond", "diamond shape"], emoji: "🔸" },
      { names: ["small blue diamond", "diamond shape"], emoji: "🔹" },
      { names: ["red triangle pointed up", "triangle"], emoji: "🔺" },
      { names: ["red triangle pointed down", "triangle"], emoji: "🔻" },
      { names: ["diamond with a dot"], emoji: "💠" },
      { names: ["radio button"], emoji: "🔘" },
      { names: ["white square button"], emoji: "🔳" },
      { names: ["black square button"], emoji: "🔲" },
    ],
  },
  {
    category: "symbols",
    items: [
      { names: ["kiss mark", "lipstick mark"], emoji: "💋" },
      { names: ["hundred points", "100"], emoji: "💯" },
      { names: ["anger symbol"], emoji: "💢" },
      { names: ["collision", "boom", "explosion"], emoji: "💥" },
      { names: ["dizzy star"], emoji: "💫" },
      { names: ["sweat droplets", "water drops"], emoji: "💦" },
      { names: ["dash cloud", "puff"], emoji: "💨" },
      { names: ["speech bubble"], emoji: "💬" },
      { names: ["thought bubble"], emoji: "💭" },
      { names: ["zzz", "sleep symbol"], emoji: "💤" },
      { names: ["bust in silhouette"], emoji: "👤" },
      { names: ["busts in silhouette"], emoji: "👥" },
      { names: ["family"], emoji: "👪" },
      { names: ["footprints"], emoji: "👣" },
      { names: ["atm sign"], emoji: "🏧" },
      { names: ["litter in bin sign"], emoji: "🚮" },
      { names: ["potable water"], emoji: "🚰" },
      { names: ["wheelchair symbol"], emoji: "♿" },
      { names: ["mens room"], emoji: "🚹" },
      { names: ["womens room"], emoji: "🚺" },
      { names: ["restroom"], emoji: "🚻" },
      { names: ["baby symbol"], emoji: "🚼" },
      { names: ["water closet"], emoji: "🚾" },
      { names: ["passport control"], emoji: "🛂" },
      { names: ["customs"], emoji: "🛃" },
      { names: ["baggage claim"], emoji: "🛄" },
      { names: ["left luggage"], emoji: "🛅" },
      { names: ["children crossing"], emoji: "🚸" },
      { names: ["no entry"], emoji: "⛔" },
      { names: ["prohibited"], emoji: "🚫" },
      { names: ["no bicycles"], emoji: "🚳" },
      { names: ["no smoking"], emoji: "🚭" },
      { names: ["no littering"], emoji: "🚯" },
      { names: ["non-potable water"], emoji: "🚱" },
      { names: ["no pedestrians"], emoji: "🚷" },
      { names: ["no mobile phones"], emoji: "📵" },
      { names: ["no one under eighteen"], emoji: "🔞" },
      { names: ["clockwise vertical arrows"], emoji: "🔃" },
      { names: ["counterclockwise arrows button"], emoji: "🔄" },
      { names: ["back arrow"], emoji: "🔙" },
      { names: ["end arrow"], emoji: "🔚" },
      { names: ["on arrow"], emoji: "🔛" },
      { names: ["soon arrow"], emoji: "🔜" },
      { names: ["top arrow"], emoji: "🔝" },
      { names: ["place of worship"], emoji: "🛐" },
      { names: ["menorah"], emoji: "🕎" },
      { names: ["dotted six pointed star"], emoji: "🔯" },
      { names: ["aries", "zodiac"], emoji: "♈" },
      { names: ["taurus", "zodiac"], emoji: "♉" },
      { names: ["gemini", "zodiac"], emoji: "♊" },
      { names: ["cancer", "zodiac"], emoji: "♋" },
      { names: ["leo", "zodiac"], emoji: "♌" },
      { names: ["virgo", "zodiac"], emoji: "♍" },
      { names: ["libra", "zodiac"], emoji: "♎" },
      { names: ["scorpius", "zodiac"], emoji: "♏" },
      { names: ["sagittarius", "zodiac"], emoji: "♐" },
      { names: ["capricorn", "zodiac"], emoji: "♑" },
      { names: ["aquarius", "zodiac"], emoji: "♒" },
      { names: ["pisces", "zodiac"], emoji: "♓" },
      { names: ["ophiuchus", "zodiac"], emoji: "⛎" },
      { names: ["shuffle tracks button"], emoji: "🔀" },
      { names: ["repeat button"], emoji: "🔁" },
      { names: ["repeat single button"], emoji: "🔂" },
      { names: ["fast forward button"], emoji: "⏩" },
      { names: ["fast reverse button"], emoji: "⏪" },
      { names: ["upwards button"], emoji: "🔼" },
      { names: ["fast up button"], emoji: "⏫" },
      { names: ["downwards button"], emoji: "🔽" },
      { names: ["fast down button"], emoji: "⏬" },
      { names: ["cinema"], emoji: "🎦" },
      { names: ["dim button"], emoji: "🔅" },
      { names: ["bright button"], emoji: "🔆" },
      { names: ["antenna bars"], emoji: "📶" },
      { names: ["wireless"], emoji: "🛜" },
      { names: ["vibration mode"], emoji: "📳" },
      { names: ["mobile phone off"], emoji: "📴" },
      { names: ["plus"], emoji: "➕" },
      { names: ["minus"], emoji: "➖" },
      { names: ["divide"], emoji: "➗" },
      { names: ["heavy equals sign"], emoji: "🟰" },
      { names: ["red question mark"], emoji: "❓" },
      { names: ["white question mark"], emoji: "❔" },
      { names: ["white exclamation mark"], emoji: "❕" },
      { names: ["red exclamation mark"], emoji: "❗" },
      { names: ["currency exchange"], emoji: "💱" },
      { names: ["heavy dollar sign"], emoji: "💲" },
      { names: ["trident emblem"], emoji: "🔱" },
      { names: ["name badge"], emoji: "📛" },
      { names: ["japanese symbol for beginner"], emoji: "🔰" },
      { names: ["hollow red circle"], emoji: "⭕" },
      { names: ["check mark button"], emoji: "✅" },
      { names: ["cross mark"], emoji: "❌" },
      { names: ["cross mark button"], emoji: "❎" },
      { names: ["curly loop"], emoji: "➰" },
      { names: ["double curly loop"], emoji: "➿" },
    ],
  },
  {
    category: "faces",
    items: [
      { names: ["grinning face", "smile face"], emoji: "😀" },
      { names: ["happy face", "smile face"], emoji: "😃" },
      { names: ["smiling face", "smile face"], emoji: "😄" },
      { names: ["beaming face", "smile face"], emoji: "😁" },
      { names: ["laughing face", "smile face"], emoji: "😆" },
      { names: ["nervous laugh", "smile face"], emoji: "😅" },
      { names: ["rofl", "laugh face"], emoji: "🤣" },
      { names: ["tears of joy", "laugh face"], emoji: "😂" },
      { names: ["slight smile", "smile face"], emoji: "🙂" },
      { names: ["upside down face"], emoji: "🙃" },
      { names: ["wink", "winking face"], emoji: "😉" },
      { names: ["blush", "smile face"], emoji: "😊" },
      { names: ["angel face", "halo"], emoji: "😇" },
      { names: ["loving face", "hearts around face"], emoji: "🥰" },
      { names: ["heart eyes", "love face"], emoji: "😍" },
      { names: ["star struck", "star eyes"], emoji: "🤩" },
      { names: ["blowing kiss", "kiss face"], emoji: "😘" },
      { names: ["kissing face", "kiss face"], emoji: "😗" },
      { names: ["kissing closed eyes", "kiss face"], emoji: "😚" },
      { names: ["kissing smile", "kiss face"], emoji: "😙" },
      { names: ["happy tear"], emoji: "🥲" },
      { names: ["yummy face", "tasty"], emoji: "😋" },
      { names: ["tongue out", "tongue face"], emoji: "😛" },
      { names: ["wink tongue", "tongue face"], emoji: "😜" },
      { names: ["zany face", "crazy face"], emoji: "🤪" },
      { names: ["squinting tongue", "tongue face"], emoji: "😝" },
      { names: ["money face"], emoji: "🤑" },
      { names: ["hugging face", "hug"], emoji: "🤗" },
      { names: ["giggling", "tee-hee"], emoji: "🤭" },
      { names: ["shushing face", "quiet"], emoji: "🤫" },
      { names: ["thinking face", "hmm"], emoji: "🤔" },
      { names: ["zipper mouth"], emoji: "🤐" },
      { names: ["raised eyebrow", "skeptical"], emoji: "🤨" },
      { names: ["neutral face", "blank face"], emoji: "😐" },
      { names: ["expressionless"], emoji: "😑" },
      { names: ["no mouth", "silent"], emoji: "😶" },
      { names: ["smirk"], emoji: "😏" },
      { names: ["unamused"], emoji: "😒" },
      { names: ["eye roll"], emoji: "🙄" },
      { names: ["grimace", "awkward"], emoji: "😬" },
      { names: ["lying face", "pinocchio"], emoji: "🤥" },
      { names: ["relieved face", "peaceful"], emoji: "😌" },
      { names: ["pensive face", "sad face"], emoji: "😔" },
      { names: ["sleepy face", "drowsy"], emoji: "😪" },
      { names: ["drooling face"], emoji: "🤤" },
      { names: ["sleeping face", "zzz"], emoji: "😴" },
      { names: ["mask face", "sick face"], emoji: "😷" },
      { names: ["thermometer face", "fever", "sick face"], emoji: "🤒" },
      { names: ["bandage face", "injured", "sick face"], emoji: "🤕" },
      { names: ["nauseated", "sick face"], emoji: "🤢" },
      { names: ["vomiting", "sick face"], emoji: "🤮" },
      { names: ["sneezing face"], emoji: "🤧" },
      { names: ["hot face", "overheated"], emoji: "🥵" },
      { names: ["cold face", "freezing"], emoji: "🥶" },
      { names: ["woozy face"], emoji: "🥴" },
      { names: ["dizzy face", "knocked out"], emoji: "😵" },
      { names: ["mind blown", "exploding head"], emoji: "🤯" },
      { names: ["cowboy face", "yeehaw"], emoji: "🤠" },
      { names: ["party face", "birthday face"], emoji: "🥳" },
      { names: ["disguise face"], emoji: "🥸" },
      { names: ["cool face", "sunglasses face"], emoji: "😎" },
      { names: ["nerd face", "geek"], emoji: "🤓" },
      { names: ["confused face"], emoji: "😕" },
      { names: ["worried face"], emoji: "😟" },
      { names: ["frowning face", "sad face"], emoji: "🙁" },
      { names: ["surprised face", "wow"], emoji: "😮" },
      { names: ["hushed face"], emoji: "😯" },
      { names: ["astonished face", "shocked"], emoji: "😲" },
      { names: ["flushed face", "embarrassed"], emoji: "😳" },
      { names: ["pleading face", "puppy eyes"], emoji: "🥺" },
      { names: ["face holding back tears"], emoji: "🥹" },
      { names: ["frowning open mouth"], emoji: "😦" },
      { names: ["anguished face"], emoji: "😧" },
      { names: ["fearful face", "scared"], emoji: "😨" },
      { names: ["anxious face", "worried"], emoji: "😰" },
      { names: ["sad relieved"], emoji: "😥" },
      { names: ["crying face", "tear"], emoji: "😢" },
      { names: ["sobbing", "crying loudly"], emoji: "😭" },
      { names: ["screaming face", "terrified"], emoji: "😱" },
      { names: ["confounded face"], emoji: "😖" },
      { names: ["persevering face"], emoji: "😣" },
      { names: ["disappointed face"], emoji: "😞" },
      { names: ["cold sweat face"], emoji: "😓" },
      { names: ["weary face"], emoji: "😩" },
      { names: ["tired face"], emoji: "😫" },
      { names: ["yawning face"], emoji: "🥱" },
      { names: ["face with look of triumph"], emoji: "😤" },
      { names: ["rage face", "furious"], emoji: "😡" },
      { names: ["angry face", "mad"], emoji: "😠" },
      { names: ["cursing face", "swearing"], emoji: "🤬" },
      { names: ["smiling devil", "imp"], emoji: "😈" },
      { names: ["angry devil"], emoji: "👿" },
      { names: ["skull"], emoji: "💀" },
      { names: ["poop", "poo"], emoji: "💩" },
      { names: ["clown face"], emoji: "🤡" },
      { names: ["ogre", "oni"], emoji: "👹" },
      { names: ["goblin", "tengu"], emoji: "👺" },
      { names: ["ghost", "boo"], emoji: "👻" },
      { names: ["alien"], emoji: "👽" },
      { names: ["alien monster", "space invader"], emoji: "👾" },
      { names: ["robot face"], emoji: "🤖" },
      { names: ["smiling cat", "cat face"], emoji: "😺" },
      { names: ["grinning cat", "cat face"], emoji: "😸" },
      { names: ["joy cat", "cat face"], emoji: "😹" },
      { names: ["heart eyes cat", "cat face"], emoji: "😻" },
      { names: ["smirk cat", "cat face"], emoji: "😼" },
      { names: ["kissing cat", "cat face"], emoji: "😽" },
      { names: ["weary cat", "cat face"], emoji: "🙀" },
      { names: ["crying cat", "cat face"], emoji: "😿" },
      { names: ["pouting cat", "cat face"], emoji: "😾" },
    ],
  },
  {
    category: "people",
    items: [
      { names: ["waving hand", "hi", "hello", "bye"], emoji: "👋" },
      { names: ["raised back hand"], emoji: "🤚" },
      { names: ["raised hand", "high five"], emoji: "✋" },
      { names: ["vulcan salute", "spock"], emoji: "🖖" },
      { names: ["ok hand", "okay"], emoji: "👌" },
      { names: ["pinched fingers", "italian hand"], emoji: "🤌" },
      { names: ["crossed fingers", "fingers crossed", "luck"], emoji: "🤞" },
      { names: ["love you gesture"], emoji: "🤟" },
      { names: ["rock on", "metal horns"], emoji: "🤘" },
      { names: ["call me hand", "shaka"], emoji: "🤙" },
      { names: ["point left"], emoji: "👈" },
      { names: ["point right"], emoji: "👉" },
      { names: ["point up"], emoji: "👆" },
      { names: ["middle finger"], emoji: "🖕" },
      { names: ["point down"], emoji: "👇" },
      { names: ["thumbs up", "like"], emoji: "👍" },
      { names: ["thumbs down", "dislike"], emoji: "👎" },
      { names: ["raised fist"], emoji: "✊" },
      { names: ["fist bump", "punch"], emoji: "👊" },
      { names: ["left fist", "fist bump"], emoji: "🤛" },
      { names: ["right fist", "fist bump"], emoji: "🤜" },
      { names: ["clapping hands", "applause"], emoji: "👏" },
      { names: ["raised hands", "hooray"], emoji: "🙌" },
      { names: ["open hands"], emoji: "👐" },
      { names: ["palms up"], emoji: "🤲" },
      { names: ["handshake"], emoji: "🤝" },
      { names: ["folded hands", "pray", "please", "thank you"], emoji: "🙏" },
      { names: ["nail polish"], emoji: "💅" },
      { names: ["selfie"], emoji: "🤳" },
      { names: ["flexed bicep", "muscle", "strong"], emoji: "💪" },
      { names: ["mechanical arm"], emoji: "🦾" },
      { names: ["mechanical leg"], emoji: "🦿" },
      { names: ["leg"], emoji: "🦵" },
      { names: ["foot"], emoji: "🦶" },
      { names: ["ear"], emoji: "👂" },
      { names: ["ear with hearing aid"], emoji: "🦻" },
      { names: ["nose"], emoji: "👃" },
      { names: ["tooth"], emoji: "🦷" },
      { names: ["bone"], emoji: "🦴" },
      { names: ["eyes"], emoji: "👀" },
      { names: ["tongue"], emoji: "👅" },
      { names: ["mouth", "lips"], emoji: "👄" },
      { names: ["baby"], emoji: "👶" },
      { names: ["boy"], emoji: "👦" },
      { names: ["girl"], emoji: "👧" },
      { names: ["blond person"], emoji: "👱" },
      { names: ["man"], emoji: "👨" },
      { names: ["woman"], emoji: "👩" },
      { names: ["old man", "grandpa"], emoji: "👴" },
      { names: ["old woman", "grandma"], emoji: "👵" },
      { names: ["frowning person"], emoji: "🙍" },
      { names: ["pouting person"], emoji: "🙎" },
      { names: ["no gesture"], emoji: "🙅" },
      { names: ["ok gesture"], emoji: "🙆" },
      { names: ["information person"], emoji: "💁" },
      { names: ["raising hand person"], emoji: "🙋" },
      { names: ["bowing person"], emoji: "🙇" },
      { names: ["facepalm"], emoji: "🤦" },
      { names: ["shrug"], emoji: "🤷" },
      { names: ["person getting massage"], emoji: "💆" },
      { names: ["person getting haircut"], emoji: "💇" },
      { names: ["person walking"], emoji: "🚶" },
      { names: ["person running"], emoji: "🏃" },
      { names: ["woman dancing"], emoji: "💃" },
      { names: ["man dancing"], emoji: "🕺" },
      { names: ["people with bunny ears"], emoji: "👯" },
      { names: ["person in bath"], emoji: "🛀" },
      { names: ["person in bed"], emoji: "🛌" },
      { names: ["women holding hands"], emoji: "👭" },
      { names: ["woman and man holding hands"], emoji: "👫" },
      { names: ["men holding hands"], emoji: "👬" },
      { names: ["couple kissing"], emoji: "💏" },
      { names: ["couple with heart"], emoji: "💑" },
    ],
  },
  {
    category: "fantasy",
    items: [
      { names: ["police officer"], emoji: "👮" },
      { names: ["guard"], emoji: "💂" },
      { names: ["ninja"], emoji: "🥷" },
      { names: ["construction worker"], emoji: "👷" },
      { names: ["prince"], emoji: "🤴" },
      { names: ["princess"], emoji: "👸" },
      { names: ["person with turban"], emoji: "👳" },
      { names: ["person with cap"], emoji: "👲" },
      { names: ["person in tuxedo"], emoji: "🤵" },
      { names: ["bride"], emoji: "👰" },
      { names: ["pregnant woman"], emoji: "🤰" },
      { names: ["breastfeeding"], emoji: "🤱" },
      { names: ["baby angel"], emoji: "👼" },
      { names: ["santa claus"], emoji: "🎅" },
      { names: ["mrs claus"], emoji: "🤶" },
      { names: ["superhero"], emoji: "🦸" },
      { names: ["supervillain"], emoji: "🦹" },
    ],
  },
  {
    category: "celebration",
    items: [
      { names: ["jack o lantern", "pumpkin", "halloween"], emoji: "🎃" },
      { names: ["christmas tree"], emoji: "🎄" },
      { names: ["fireworks"], emoji: "🎆" },
      { names: ["sparkler"], emoji: "🎇" },
      { names: ["sparkles"], emoji: "✨" },
      { names: ["balloon"], emoji: "🎈" },
      { names: ["party popper", "party"], emoji: "🎉" },
      { names: ["confetti ball"], emoji: "🎊" },
      { names: ["tanabata tree"], emoji: "🎋" },
      { names: ["pine decoration"], emoji: "🎍" },
      { names: ["japanese dolls"], emoji: "🎎" },
      { names: ["carp streamer"], emoji: "🎏" },
      { names: ["wind chime"], emoji: "🎐" },
      { names: ["moon viewing ceremony"], emoji: "🎑" },
      { names: ["ribbon"], emoji: "🎀" },
      { names: ["wrapped gift", "present"], emoji: "🎁" },
      { names: ["ticket"], emoji: "🎫" },
    ],
  },
  {
    category: "flags",
    items: [
      { names: ["chequered flag"], emoji: "🏁" },
      { names: ["triangular flag"], emoji: "🚩" },
      { names: ["crossed flags"], emoji: "🎌" },
      { names: ["black flag"], emoji: "🏴" },
    ],
  },
];

// =============================================================================
// Lookup Maps (built at module load time)
// =============================================================================

/** Map from name/alias -> first emoji that uses it */
const nameToEmoji = new Map<string, string>();

/** Map from name/alias -> all emojis that use it (for similarity detection) */
const nameToAllEmojis = new Map<string, string[]>();

/** Map from emoji -> all its names */
const emojiToNames = new Map<string, string[]>();

/** Map from emoji -> category */
const emojiToCategory = new Map<string, string>();

/** Map from category -> emoji items */
const categoryToItems = new Map<string, EmojiItem[]>();

// Build all lookup maps
EMOJI_DATABASE.forEach((cat) => {
  categoryToItems.set(cat.category, cat.items);
  cat.items.forEach((item) => {
    emojiToNames.set(item.emoji, item.names);
    emojiToCategory.set(item.emoji, cat.category);
    item.names.forEach((name) => {
      const lowerName = name.toLowerCase();
      // First emoji wins for direct lookup
      if (!nameToEmoji.has(lowerName)) {
        nameToEmoji.set(lowerName, item.emoji);
      }
      // Track all emojis that share this name (for similarity)
      if (!nameToAllEmojis.has(lowerName)) {
        nameToAllEmojis.set(lowerName, []);
      }
      nameToAllEmojis.get(lowerName)!.push(item.emoji);
    });
  });
});

// =============================================================================
// Public API
// =============================================================================

/**
 * Look up an emoji by name (case-insensitive)
 * Returns the FIRST emoji that matches (by definition order)
 */
export function findEmojiByName(
  name: string,
): { emoji: string; category: string } | null {
  const emoji = nameToEmoji.get(name.toLowerCase().trim());
  if (!emoji) return null;
  const category = emojiToCategory.get(emoji);
  if (!category) return null;
  return { emoji, category };
}

/**
 * Get all emojis in a category
 */
export function getEmojisByCategory(category: string): EmojiItem[] {
  return categoryToItems.get(category) || [];
}

/**
 * Get the category for an emoji
 */
export function getCategoryByEmoji(emoji: string): string | null {
  return emojiToCategory.get(emoji) || null;
}

/**
 * Check if two emojis are visually similar (share any name)
 */
export function areVisuallySimilar(emoji1: string, emoji2: string): boolean {
  const names1 = emojiToNames.get(emoji1);
  const names2 = emojiToNames.get(emoji2);
  if (!names1 || !names2) return false;

  const names1Lower = new Set(names1.map((n) => n.toLowerCase()));
  return names2.some((n) => names1Lower.has(n.toLowerCase()));
}

/**
 * Get random distractors from the same category (excluding visually similar)
 */
export function getDistractors(
  targetEmoji: string,
  category: string,
  count: number = 2,
): string[] {
  const categoryItems = getEmojisByCategory(category);

  // Filter out the target and any visually similar emojis
  const validDistractors = categoryItems.filter(
    (item) =>
      item.emoji !== targetEmoji &&
      !areVisuallySimilar(targetEmoji, item.emoji),
  );

  // Shuffle and take count items
  const shuffled = shuffle([...validDistractors]);
  return shuffled.slice(0, count).map((item) => item.emoji);
}

/**
 * Get all available emoji names for suggestions (shortest name for each emoji)
 */
export function getAllEmojiNames(): string[] {
  const names: string[] = [];
  EMOJI_DATABASE.forEach((cat) => {
    cat.items.forEach((item) => {
      // Pick the shortest name for display
      const shortest = item.names.reduce((a, b) =>
        a.length <= b.length ? a : b,
      );
      names.push(shortest);
    });
  });
  return names;
}
